### ISSUE TITLE
SyntaxError: unexpected token: ':'

### ISSUE THREAD

**Issue by artelse** [sobstel/jsonp.js#3]
I get this error when I try to get some json data from a local server.
Any idea why that happens, json data looks normal.

**Comment by sobstel** [comment]
Hard to say without more info (code samples, error reports/dumps with calls tack etc) to debug.

Do you correctly wrap json with callback function?

**Comment by artelse** [comment]
I came here from [your stackoverflow example](https://stackoverflow.com/questions/6132796/how-to-make-a-jsonp-request-from-javascript-without-jquery) where `some_url` is my local server of course.
I suspect I should add the callback? But how, isn't `handleStuff` the callback passed?
```
var $jsonp = (function(){
  var that = {};

  that.send = function(src, options) {
    var callback_name = options.callbackName || 'callback',
      on_success = options.onSuccess || function(){},
      on_timeout = options.onTimeout || function(){},
      timeout = options.timeout || 10; // sec

    var timeout_trigger = window.setTimeout(function(){
      window[callback_name] = function(){};
      on_timeout();
    }, timeout * 1000);

    window[callback_name] = function(data){
      window.clearTimeout(timeout_trigger);
      on_success(data);
    }

    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.async = true;
    script.src = src;

    document.getElementsByTagName('head')[0].appendChild(script);
  }

  return that;
})();

$jsonp.send('some_url?callback=handleStuff', {
    callbackName: 'handleStuff',
    onSuccess: function(json){
        console.log('success!', json);
    },
    onTimeout: function(){
        console.log('timeout!');
    },
    timeout: 5
});
```

**Comment by sobstel** [comment]
You need to wrap up your JSON (at `some_url`) with a function for JSONP to work. 

Adding `?callback=handleStuff` to `some_url` is not needed. It's just a common pattern to pass it to a script that generates JSON to have dynamic function names. It's all implemented at your side.

**Comment by artelse** [comment]
Turned out a not secure (http instead of https) request was blocked.
